### PR TITLE
Latest dts changes should now be available for all supported modules/variants

### PR DESCRIPTION
**Pull request by QuickJack**
The official kernel for the BBB (4.1.x-bone) as well as the 4.1.x-ti kernels should be fully supported.

### CODE REVIEW

**Comment by QuickJack** [comment]
I have just compiled/tested the driver under 4.4.21-bone-rt-r13. Unfortunately, it does not work yet.

**Comment by QuickJack** [comment]
Hi Jonathan, do you see any problems with this Pull Request? If so, please comment.

**Comment by QuickJack** [comment]
This should close#23.

**Comment by fpga-logi-fam** [comment]
I haven't had a chance to test, but i believe in the quality of your work.
Thanks a lot !

**Pull request merged**
