### PR TITLE
Better support for newer/different kernels

### PR DESCRIPTION
**Pull request by QuickJack**

### CODE REVIEW

**Comment by jpiat** [comment]
Did you succefuly test a debian/ubuntu based image with this changes ? Could you report the kernel version it compiles with ?

**Comment by QuickJack** [comment]
I am still using a 4.1.x bone-rt kernel which is working fine. I also did a quick test of the ti kernel. I will soon start testing other/newer kernels.

**Comment by QuickJack** [comment]
The current logibone driver plays nicely with the alternative 4.1.x-ti-rt kernel. I have successfully tested the following kernels using an up to date Xenial rootfs

Kernel			cpu load [%]	systemd-analyze	DMA Engine
4.1.24-bone-rt-r21	16.9..17.3%	7.145s/18.921s		EDMA/DMA Engine
4.1.30-ti-rt-r69		23.5..23.7%	9.250/25.406s		Linux DMA Engine

I also tested 4.4.16-bone-rt-r11 which resulted in a dmesg log entry like „edma 49000000.edma: Ignoring eDMA instance for linking“. Additionally, the testing app hangs and cannot be killed. This kernel does also use the Linux DMA Engine. They seem to have modified the DMA part again. The logibone driver does currently not support this kernel.

The EDMA performace of the ti-rt kernel is still far behind that of the bone-rt kernel. CPU load is about 37% higher. Kernel loading time is 30% higher and loading of the userspace part is 34% slower. Based on these results I would clearly suggest to stick with the 4.1x-bone-rt kernel for the time beeing.

**Comment by fpga-logi-fam** [comment]
Thanks Martin for all this work. Does 4.1 kernel support device tree
overlays or do we still have to stick with static device tree ? I know that
4.4 on raspberry pi has overlay support but i don't know if 4.1 does.

**Comment by QuickJack** [comment]
Both 4.1 and 4.4 do have cape_manager support and thus allow to dynamically load overlays. I guess that the patched dtc version which is required to generate the overlays for 4.1 cannot be used for 4.4 when it comes to using EDMA transfers.

**Pull request merged**
